import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9fa",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#dde3eb",
        "on-surface": "#191c1d",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "primary": "#000000",
        "error": "#ba1a1a",
        "surface-container-high": "#e7e8e9",
        "primary-container": "#0d1c32",
        "on-primary-fixed": "#0d1c32",
        "on-background": "#191c1d",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed-variant": "#41474e",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b9c7e4",
        "on-secondary-container": "#54647a",
        "on-tertiary-container": "#7e848c",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-container": "#76849f",
        "inverse-surface": "#2e3132",
        "on-surface-variant": "#44474d",
        "surface-variant": "#e1e3e4",
        "tertiary-container": "#161c22",
        "secondary": "#505f76",
        "on-secondary-fixed-variant": "#38485d",
        "background": "#f8f9fa",
        "surface-tint": "#515f78",
        "outline-variant": "#c5c6cd",
        "outline": "#75777e",
        "surface-dim": "#d9dadb",
        "secondary-fixed": "#d3e4fe",
        "on-secondary-fixed": "#0b1c30",
        "on-primary-fixed-variant": "#39475f",
        "tertiary-fixed-dim": "#c1c7cf",
        "secondary-container": "#d0e1fb",
        "inverse-primary": "#b9c7e4",
        "on-tertiary-fixed": "#161c22",
        "primary-fixed": "#d6e3ff",
        "on-secondary": "#ffffff",
        "tertiary": "#000000",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9fa",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "success": "#059669",
        "warning": "#d97706",
        "warning-dark": "#b45309",
        "info": "#0284c7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "unit": "4px",
        "container-padding-desktop": "40px",
        "stack-sm": "8px",
        "container-padding-mobile": "20px",
        "stack-lg": "32px",
        "gutter": "16px"
      },
      fontFamily: {
        "headline-md": ["var(--font-sans)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-mono)", "Geist", "monospace"],
        "body-md": ["var(--font-sans)", "Inter", "sans-serif"],
        "label-md": ["var(--font-mono)", "Geist", "monospace"],
        "body-lg": ["var(--font-sans)", "Inter", "sans-serif"],
        "display": ["var(--font-sans)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-sans)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-sans)", "Inter", "sans-serif"],
        "sans": ["var(--font-sans)", "Inter", "sans-serif"],
        "mono": ["var(--font-mono)", "Geist", "monospace"],
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      },
      boxShadow: {
        'architectural': '0px 12px 32px rgba(10, 25, 47, 0.04)',
      },
    },
  },
  plugins: [],
};

export default config;
